version: "2.2"

services:
  sqlite:
    container_name: MoneyTrk-db
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/
    restart: always

  app:
    container_name: MoneyTrk-bot
    build: .
    volumes:
      - ./app:/project/app
      - ./db:/project/db
    restart: always

  grafana:
    container_name: MoneyTrk-graf
    image: grafana/grafana
    depends_on:
      - sqlite
      - app
    ports:
      - "3000:3000"
    user: "$UID:$GID"
    volumes:
      - ./db:/root/db:ro
      - ./grafana/plugins:/var/lib/grafana/plugins/:rw
      - ./grafana/conf:/var/lib/grafana/conf/:rw

  nginx:
    container_name: MoneyTrk-ingress
    image: nginx:latest
    depends_on:
      - grafana
    ports:
      - 80:80
      - 443:443
    links:
      - grafana:grafana
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/certbot:/var/www/certbot
      - ./nginx/ssl/conf:/etc/nginx/ssl:ro
    restart: always
  
  certbot:
    container_name: MoneyTrk-certbot
    image: certbot/certbot:latest
    volumes:
      - ./nginx/ssl/certbot:/var/www/certbot:rw
      - ./nginx/ssl/conf:/etc/letsencrypt/:rw
